[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors = ["Felix Böhm <felix@felixboehm.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
jupyterlab = "^3.4.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
